language: ruby
rvm:
  - 2.2.2

env:
  - DB=sqlite
  - DB=postgresql

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test' -U postgres

script:
  - bundle exec rake --trace db:migrate RAILS_ENV=test
  - bundle exec cucumber
  - bundle exec rspec

addons:
    code_climate:
        repo_token: bcc51d0ee53a134dbbab7023cceacb480bb7360f84812025cad7f0afccfde69e